/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IExternalKycList } from "./IExternalKycList";
export type { IExternalKycListManagement } from "./IExternalKycListManagement";
