/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClaimTopicsRegistry } from "./ClaimTopicsRegistry";
export type { IdentityRegistry } from "./IdentityRegistry";
export type { IdentityRegistryStorage } from "./IdentityRegistryStorage";
export type { TrustedIssuersRegistry } from "./TrustedIssuersRegistry";
