/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClearingStorageWrapper1__factory } from "./ClearingStorageWrapper1__factory";
export { ClearingStorageWrapper2__factory } from "./ClearingStorageWrapper2__factory";
