/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Freeze__factory } from "./Freeze__factory";
export { FreezeFacet__factory } from "./FreezeFacet__factory";
