/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEquity__factory } from "./IEquity__factory";
export { IEquityStorageWrapper__factory } from "./IEquityStorageWrapper__factory";
