/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IDiamondLoupe {
  export type FacetStruct = {
    id: PromiseOrValue<BytesLike>;
    addr: PromiseOrValue<string>;
    selectors: PromiseOrValue<BytesLike>[];
    interfaceIds: PromiseOrValue<BytesLike>[];
  };

  export type FacetStructOutput = [string, string, string[], string[]] & {
    id: string;
    addr: string;
    selectors: string[];
    interfaceIds: string[];
  };
}

export interface IDiamondLoupeInterface extends utils.Interface {
  functions: {
    "getFacet(bytes32)": FunctionFragment;
    "getFacetAddress(bytes4)": FunctionFragment;
    "getFacetAddresses()": FunctionFragment;
    "getFacetAddressesByPage(uint256,uint256)": FunctionFragment;
    "getFacetIdBySelector(bytes4)": FunctionFragment;
    "getFacetIds()": FunctionFragment;
    "getFacetIdsByPage(uint256,uint256)": FunctionFragment;
    "getFacetSelectors(bytes32)": FunctionFragment;
    "getFacetSelectorsByPage(bytes32,uint256,uint256)": FunctionFragment;
    "getFacetSelectorsLength(bytes32)": FunctionFragment;
    "getFacets()": FunctionFragment;
    "getFacetsByPage(uint256,uint256)": FunctionFragment;
    "getFacetsLength()": FunctionFragment;
    "getStaticFunctionSelectors()": FunctionFragment;
    "getStaticInterfaceIds()": FunctionFragment;
    "getStaticResolverKey()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getFacet"
      | "getFacetAddress"
      | "getFacetAddresses"
      | "getFacetAddressesByPage"
      | "getFacetIdBySelector"
      | "getFacetIds"
      | "getFacetIdsByPage"
      | "getFacetSelectors"
      | "getFacetSelectorsByPage"
      | "getFacetSelectorsLength"
      | "getFacets"
      | "getFacetsByPage"
      | "getFacetsLength"
      | "getStaticFunctionSelectors"
      | "getStaticInterfaceIds"
      | "getStaticResolverKey"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFacet",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetAddress",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetAddressesByPage",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetIdBySelector",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetIdsByPage",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetSelectors",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetSelectorsByPage",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetSelectorsLength",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "getFacets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFacetsByPage",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStaticFunctionSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStaticInterfaceIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStaticResolverKey",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getFacet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFacetAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetAddressesByPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetIdBySelector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetIdsByPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetSelectorsByPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetSelectorsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFacets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFacetsByPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStaticFunctionSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStaticInterfaceIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStaticResolverKey",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDiamondLoupe extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDiamondLoupeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getFacet(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [IDiamondLoupe.FacetStructOutput] & {
        facet_: IDiamondLoupe.FacetStructOutput;
      }
    >;

    getFacetAddress(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { facetAddress_: string }>;

    getFacetAddresses(
      overrides?: CallOverrides
    ): Promise<[string[]] & { facetAddresses_: string[] }>;

    getFacetAddressesByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { facetAddresses_: string[] }>;

    getFacetIdBySelector(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { facetId_: string }>;

    getFacetIds(
      overrides?: CallOverrides
    ): Promise<[string[]] & { facetIds_: string[] }>;

    getFacetIdsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { facetIds_: string[] }>;

    getFacetSelectors(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { facetSelectors_: string[] }>;

    getFacetSelectorsByPage(
      _facetId: PromiseOrValue<BytesLike>,
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { facetSelectors_: string[] }>;

    getFacetSelectorsLength(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { facetSelectorsLength_: BigNumber }>;

    getFacets(
      overrides?: CallOverrides
    ): Promise<
      [IDiamondLoupe.FacetStructOutput[]] & {
        facets_: IDiamondLoupe.FacetStructOutput[];
      }
    >;

    getFacetsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IDiamondLoupe.FacetStructOutput[]] & {
        facets_: IDiamondLoupe.FacetStructOutput[];
      }
    >;

    getFacetsLength(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { facetsLength_: BigNumber }>;

    getStaticFunctionSelectors(
      overrides?: CallOverrides
    ): Promise<[string[]] & { staticFunctionSelectors_: string[] }>;

    getStaticInterfaceIds(
      overrides?: CallOverrides
    ): Promise<[string[]] & { staticInterfaceIds_: string[] }>;

    getStaticResolverKey(
      overrides?: CallOverrides
    ): Promise<[string] & { staticResolverKey_: string }>;
  };

  getFacet(
    _facetId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<IDiamondLoupe.FacetStructOutput>;

  getFacetAddress(
    _selector: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getFacetAddresses(overrides?: CallOverrides): Promise<string[]>;

  getFacetAddressesByPage(
    _pageIndex: PromiseOrValue<BigNumberish>,
    _pageLength: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getFacetIdBySelector(
    _selector: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getFacetIds(overrides?: CallOverrides): Promise<string[]>;

  getFacetIdsByPage(
    _pageIndex: PromiseOrValue<BigNumberish>,
    _pageLength: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getFacetSelectors(
    _facetId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getFacetSelectorsByPage(
    _facetId: PromiseOrValue<BytesLike>,
    _pageIndex: PromiseOrValue<BigNumberish>,
    _pageLength: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getFacetSelectorsLength(
    _facetId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFacets(
    overrides?: CallOverrides
  ): Promise<IDiamondLoupe.FacetStructOutput[]>;

  getFacetsByPage(
    _pageIndex: PromiseOrValue<BigNumberish>,
    _pageLength: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IDiamondLoupe.FacetStructOutput[]>;

  getFacetsLength(overrides?: CallOverrides): Promise<BigNumber>;

  getStaticFunctionSelectors(overrides?: CallOverrides): Promise<string[]>;

  getStaticInterfaceIds(overrides?: CallOverrides): Promise<string[]>;

  getStaticResolverKey(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getFacet(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IDiamondLoupe.FacetStructOutput>;

    getFacetAddress(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getFacetAddresses(overrides?: CallOverrides): Promise<string[]>;

    getFacetAddressesByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getFacetIdBySelector(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getFacetIds(overrides?: CallOverrides): Promise<string[]>;

    getFacetIdsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getFacetSelectors(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getFacetSelectorsByPage(
      _facetId: PromiseOrValue<BytesLike>,
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getFacetSelectorsLength(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacets(
      overrides?: CallOverrides
    ): Promise<IDiamondLoupe.FacetStructOutput[]>;

    getFacetsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IDiamondLoupe.FacetStructOutput[]>;

    getFacetsLength(overrides?: CallOverrides): Promise<BigNumber>;

    getStaticFunctionSelectors(overrides?: CallOverrides): Promise<string[]>;

    getStaticInterfaceIds(overrides?: CallOverrides): Promise<string[]>;

    getStaticResolverKey(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getFacet(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetAddress(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    getFacetAddressesByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetIdBySelector(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetIds(overrides?: CallOverrides): Promise<BigNumber>;

    getFacetIdsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetSelectors(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetSelectorsByPage(
      _facetId: PromiseOrValue<BytesLike>,
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetSelectorsLength(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacets(overrides?: CallOverrides): Promise<BigNumber>;

    getFacetsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetsLength(overrides?: CallOverrides): Promise<BigNumber>;

    getStaticFunctionSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    getStaticInterfaceIds(overrides?: CallOverrides): Promise<BigNumber>;

    getStaticResolverKey(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getFacet(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetAddress(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetAddresses(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFacetAddressesByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetIdBySelector(
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetIds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFacetIdsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetSelectors(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetSelectorsByPage(
      _facetId: PromiseOrValue<BytesLike>,
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetSelectorsLength(
      _facetId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFacetsByPage(
      _pageIndex: PromiseOrValue<BigNumberish>,
      _pageLength: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStaticFunctionSelectors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStaticInterfaceIds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStaticResolverKey(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
