/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ScheduledSnapshotsStorageWrapperRead__factory } from "./ScheduledSnapshotsStorageWrapperRead__factory";
