/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICorporateActionsStorageWrapper,
  ICorporateActionsStorageWrapperInterface,
} from "../../../../../contracts/layer_1/interfaces/corporateActions/ICorporateActionsStorageWrapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "firstDate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "secondDate",
        type: "uint256",
      },
    ],
    name: "WrongDates",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "actionType",
        type: "bytes32",
      },
    ],
    name: "WrongIndexForAction",
    type: "error",
  },
] as const;

export class ICorporateActionsStorageWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): ICorporateActionsStorageWrapperInterface {
    return new utils.Interface(
      _abi
    ) as ICorporateActionsStorageWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICorporateActionsStorageWrapper {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICorporateActionsStorageWrapper;
  }
}
